// Mock product data for Kosen Systems storefront
export const products = [
  {
    id: 'ks-mp1584',
    name: 'KS-MP1584 DC-DC Buck Converter',
    shortName: 'KS-MP1584 Buck Converter',
    price: 249,
    originalPrice: 349,
    description: 'High-efficiency adjustable DC-DC step-down converter module based on the MP1584 chip. Perfect for industrial, automotive, and embedded power supply applications.',
    category: 'buck-converters',
    images: ['/images/products/mp1584-1.jpg', '/images/products/mp1584-2.jpg'],
    datasheet: '/docs/mp1584-datasheet.pdf',
    inStock: true,
    stock: 150,
    badge: 'Best Seller',
    specs: {
      'Input Voltage': '4.5V – 28V DC',
      'Output Voltage': '0.8V – 20V (Adjustable)',
      'Max Output Current': '3A',
      'Conversion Efficiency': 'Up to 96%',
      'Switching Frequency': '1.5MHz',
      'Operating Temperature': '-40°C to +85°C',
      'Dimensions': '22mm × 17mm × 4mm',
      'Protection': 'Over-current, Thermal Shutdown',
    },
    features: [
      'Ultra-compact SMD module design',
      'Wide input voltage range',
      'Trimmable output via on-board potentiometer',
      'Integrated thermal shutdown',
      'Low quiescent current',
    ],
  },
  {
    id: 'ks-lm2596',
    name: 'KS-LM2596 Step-Down Voltage Regulator',
    shortName: 'KS-LM2596 Regulator',
    price: 199,
    originalPrice: 279,
    description: 'Robust step-down voltage regulator module with adjustable output. Ideal for battery-powered systems and solar charge controllers.',
    category: 'buck-converters',
    images: ['/images/products/lm2596-1.jpg'],
    datasheet: '/docs/lm2596-datasheet.pdf',
    inStock: true,
    stock: 200,
    badge: 'Popular',
    specs: {
      'Input Voltage': '4.5V – 40V DC',
      'Output Voltage': '1.23V – 37V (Adjustable)',
      'Max Output Current': '3A (2A recommended)',
      'Conversion Efficiency': 'Up to 92%',
      'Switching Frequency': '150kHz',
      'Operating Temperature': '-45°C to +85°C',
      'Dimensions': '42mm × 20mm × 14mm',
      'Protection': 'Short Circuit, Thermal',
    },
    features: [
      'Wide input/output voltage range',
      'On-board voltage display (optional)',
      'Screw terminal connections',
      'Reverse polarity protection',
      'High power density',
    ],
  },
  {
    id: 'ks-xl4015',
    name: 'KS-XL4015 5A Buck Converter Module',
    shortName: 'KS-XL4015 5A Module',
    price: 399,
    originalPrice: 499,
    description: 'High-current 5A DC-DC buck converter module for demanding power supply applications. Features adjustable voltage and current limiting.',
    category: 'buck-converters',
    images: ['/images/products/xl4015-1.jpg'],
    datasheet: '/docs/xl4015-datasheet.pdf',
    inStock: true,
    stock: 75,
    badge: 'New',
    specs: {
      'Input Voltage': '8V – 36V DC',
      'Output Voltage': '1.25V – 32V (Adjustable)',
      'Max Output Current': '5A',
      'Conversion Efficiency': 'Up to 96%',
      'Switching Frequency': '180kHz',
      'Operating Temperature': '-40°C to +85°C',
      'Dimensions': '51mm × 26mm × 14mm',
      'Protection': 'OCP, OVP, Thermal',
    },
    features: [
      'High current 5A output capability',
      'CC/CV adjustable output',
      'LED charge indicator',
      'Heatsink included',
      'Ideal for lithium battery charging',
    ],
  },
  {
    id: 'ks-esp32-iot',
    name: 'KS-ESP32 IoT Development Board',
    shortName: 'KS-ESP32 IoT Board',
    price: 599,
    originalPrice: 749,
    description: 'Feature-rich ESP32-based IoT development board with integrated sensors, connectivity options, and Kosen power management system.',
    category: 'iot-boards',
    images: ['/images/products/esp32-1.jpg'],
    datasheet: '/docs/esp32-iot-datasheet.pdf',
    inStock: true,
    stock: 50,
    badge: 'Featured',
    specs: {
      'Microcontroller': 'ESP32-WROOM-32E',
      'Clock Speed': 'Dual-core 240MHz',
      'Flash Memory': '4MB',
      'SRAM': '520KB',
      'WiFi': '802.11 b/g/n',
      'Bluetooth': 'BLE 4.2',
      'GPIO Pins': '30',
      'Power Supply': '5V USB / 3.3V regulated',
    },
    features: [
      'Dual-core Xtensa LX6 processor',
      'Built-in WiFi & Bluetooth',
      'Integrated temperature & humidity sensor',
      'USB-C programming interface',
      'Arduino & MicroPython compatible',
      'Kosen KS-MP1584 onboard power regulation',
    ],
  },
  {
    id: 'ks-relay-4ch',
    name: 'KS-4CH Relay Module',
    shortName: 'KS-4CH Relay Module',
    price: 349,
    originalPrice: 449,
    description: '4-channel relay module with optocoupler isolation. Designed for industrial automation, home automation, and IoT control applications.',
    category: 'modules',
    images: ['/images/products/relay-1.jpg'],
    datasheet: '/docs/relay-4ch-datasheet.pdf',
    inStock: true,
    stock: 120,
    badge: null,
    specs: {
      'Channels': '4',
      'Relay Type': 'SPDT (1NO + 1NC)',
      'Coil Voltage': '5V DC',
      'Contact Rating': '10A @ 250VAC / 30VDC',
      'Trigger': 'Active Low (with jumper config)',
      'Isolation': 'Optocoupler',
      'Dimensions': '75mm × 55mm × 20mm',
      'Indicator': 'Per-channel LED',
    },
    features: [
      'Optocoupler-isolated inputs',
      'High-current relay contacts',
      'Status LED per channel',
      'Mounting holes included',
      'Arduino / ESP32 compatible',
    ],
  },
  {
    id: 'ks-sensor-kit',
    name: 'KS-Sensor Starter Kit',
    shortName: 'KS-Sensor Kit',
    price: 899,
    originalPrice: 1199,
    description: 'Comprehensive sensor kit for IoT and embedded projects. Includes temperature, humidity, motion, light, and gas sensors with documentation.',
    category: 'accessories',
    images: ['/images/products/sensor-kit-1.jpg'],
    datasheet: null,
    inStock: true,
    stock: 30,
    badge: 'Bundle',
    specs: {
      'Sensors Included': '15',
      'Compatible With': 'Arduino, ESP32, Raspberry Pi',
      'Voltage Levels': '3.3V / 5V',
      'Documentation': 'Full guide with examples',
      'Connectors': 'Dupont & JST',
      'Storage Case': 'Included',
    },
    features: [
      'DHT22 Temperature & Humidity',
      'PIR Motion Sensor',
      'LDR Light Sensor',
      'MQ-2 Gas Sensor',
      'Ultrasonic Distance Sensor',
      'Complete wiring diagrams included',
    ],
  },
];

export const categories = [
  {
    id: 'buck-converters',
    name: 'DC-DC Buck Converters',
    description: 'High-efficiency step-down voltage converters for power management',
    icon: '⚡',
    productCount: 3,
  },
  {
    id: 'iot-boards',
    name: 'IoT Development Boards',
    description: 'WiFi & Bluetooth enabled microcontroller boards for IoT',
    icon: '📡',
    productCount: 1,
  },
  {
    id: 'modules',
    name: 'Control Modules',
    description: 'Relay, motor driver, and industrial control modules',
    icon: '🔧',
    productCount: 1,
  },
  {
    id: 'accessories',
    name: 'Kits & Accessories',
    description: 'Sensor kits, cables, and development accessories',
    icon: '🧰',
    productCount: 1,
  },
];

export const tutorials = [
  {
    id: 'tut-mp1584-guide',
    title: 'Getting Started with the KS-MP1584 Buck Converter',
    excerpt: 'Learn how to connect, configure, and optimize your KS-MP1584 for various power supply scenarios.',
    productId: 'ks-mp1584',
    category: 'Getting Started',
    readTime: '8 min',
    difficulty: 'Beginner',
  },
  {
    id: 'tut-esp32-iot',
    title: 'Building an IoT Weather Station with KS-ESP32',
    excerpt: 'Step-by-step guide to build a WiFi-connected weather station using the KS-ESP32 IoT Board.',
    productId: 'ks-esp32-iot',
    category: 'Projects',
    readTime: '15 min',
    difficulty: 'Intermediate',
  },
  {
    id: 'tut-solar-charger',
    title: 'Solar Battery Charger with KS-XL4015',
    excerpt: 'Design a solar-powered lithium battery charger using the KS-XL4015 CC/CV buck converter.',
    productId: 'ks-xl4015',
    category: 'Projects',
    readTime: '12 min',
    difficulty: 'Intermediate',
  },
  {
    id: 'tut-home-automation',
    title: 'Home Automation with KS-4CH Relay & ESP32',
    excerpt: 'Control home appliances remotely using the relay module with ESP32 and a mobile app.',
    productId: 'ks-relay-4ch',
    category: 'Projects',
    readTime: '20 min',
    difficulty: 'Advanced',
  },
];

export const featuredProducts = products.filter(p =>
  ['ks-mp1584', 'ks-esp32-iot', 'ks-xl4015', 'ks-sensor-kit'].includes(p.id)
);

export const getProductById = (id) => products.find(p => p.id === id);

export const getProductsByCategory = (categoryId) =>
  products.filter(p => p.category === categoryId);
